services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # app:
  #   image: your-app-image:latest
  #   container_name: my-app
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db

volumes:
  pgdata:
